services:
  redisinsight:
    image: redislabs/redisinsight:1.12.0
    restart: always
    ports:
      - "8001:8001"
    networks:
      - service-networks

  # admin:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8081:8080
  #   networks:
  #     - service-networks
  
  # test:
  #   build:
  #     context: ./test
  #     dockerfile: TestDockerfile
  #   image: STCVideoAnalysis/test:lastest
  #   tty: true
  #   # restart: always
  #   ports:
  #     - 5001:5001
  #   volumes:
  #     - ./test:/app
  #   command: sh -c "cd /app && python SiemensGO.py"
  #   networks:
  #     - service-networks

networks:
  service-networks:
    driver: bridge
